//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.Shared.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessBishop.
        /// </summary>
        public static string ChessBishop {
            get {
                return ResourceManager.GetString("ChessBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessHorse.
        /// </summary>
        public static string ChessHorse {
            get {
                return ResourceManager.GetString("ChessHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessKing.
        /// </summary>
        public static string ChessKing {
            get {
                return ResourceManager.GetString("ChessKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessPawn.
        /// </summary>
        public static string ChessPawn {
            get {
                return ResourceManager.GetString("ChessPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessQueen.
        /// </summary>
        public static string ChessQueen {
            get {
                return ResourceManager.GetString("ChessQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessTower.
        /// </summary>
        public static string ChessTower {
            get {
                return ResourceManager.GetString("ChessTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        public static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mout.
        /// </summary>
        public static string Mount {
            get {
                return ResourceManager.GetString("Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        public static string Ninja {
            get {
                return ResourceManager.GetString("Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palm.
        /// </summary>
        public static string Palm {
            get {
                return ResourceManager.GetString("Palm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        public static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
