//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.Shared.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessBishop.
        /// </summary>
        public static string ChessBishop {
            get {
                return ResourceManager.GetString("ChessBishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessHorse.
        /// </summary>
        public static string ChessHorse {
            get {
                return ResourceManager.GetString("ChessHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessKing.
        /// </summary>
        public static string ChessKing {
            get {
                return ResourceManager.GetString("ChessKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessPawn.
        /// </summary>
        public static string ChessPawn {
            get {
                return ResourceManager.GetString("ChessPawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessQueen.
        /// </summary>
        public static string ChessQueen {
            get {
                return ResourceManager.GetString("ChessQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessTower.
        /// </summary>
        public static string ChessTower {
            get {
                return ResourceManager.GetString("ChessTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        public static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitHelper.
        /// </summary>
        public static string HobbitHelper {
            get {
                return ResourceManager.GetString("HobbitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitLeader.
        /// </summary>
        public static string HobbitLeader {
            get {
                return ResourceManager.GetString("HobbitLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitMinorWizzard.
        /// </summary>
        public static string HobbitMinorWizzard {
            get {
                return ResourceManager.GetString("HobbitMinorWizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitRingBearer.
        /// </summary>
        public static string HobbitRingBearer {
            get {
                return ResourceManager.GetString("HobbitRingBearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitSoldier.
        /// </summary>
        public static string HobbitSoldier {
            get {
                return ResourceManager.GetString("HobbitSoldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitWarrior.
        /// </summary>
        public static string HobbitWarrior {
            get {
                return ResourceManager.GetString("HobbitWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbitWizzard.
        /// </summary>
        public static string HobbitWizzard {
            get {
                return ResourceManager.GetString("HobbitWizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRAS.
        /// </summary>
        public static string LOTRAS {
            get {
                return ResourceManager.GetString("LOTRAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRFG.
        /// </summary>
        public static string LOTRFG {
            get {
                return ResourceManager.GetString("LOTRFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRGN.
        /// </summary>
        public static string LOTRGN {
            get {
                return ResourceManager.GetString("LOTRGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRGW.
        /// </summary>
        public static string LOTRGW {
            get {
                return ResourceManager.GetString("LOTRGW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRLN.
        /// </summary>
        public static string LOTRLN {
            get {
                return ResourceManager.GetString("LOTRLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRMT.
        /// </summary>
        public static string LOTRMT {
            get {
                return ResourceManager.GetString("LOTRMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRPT.
        /// </summary>
        public static string LOTRPT {
            get {
                return ResourceManager.GetString("LOTRPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRSO.
        /// </summary>
        public static string LOTRSO {
            get {
                return ResourceManager.GetString("LOTRSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRSS.
        /// </summary>
        public static string LOTRSS {
            get {
                return ResourceManager.GetString("LOTRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mout.
        /// </summary>
        public static string Mount {
            get {
                return ResourceManager.GetString("Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        public static string Ninja {
            get {
                return ResourceManager.GetString("Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palm.
        /// </summary>
        public static string Palm {
            get {
                return ResourceManager.GetString("Palm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionAG.
        /// </summary>
        public static string SilmarillionAG {
            get {
                return ResourceManager.GetString("SilmarillionAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionEO.
        /// </summary>
        public static string SilmarillionEO {
            get {
                return ResourceManager.GetString("SilmarillionEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionIU.
        /// </summary>
        public static string SilmarillionIU {
            get {
                return ResourceManager.GetString("SilmarillionIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionMM.
        /// </summary>
        public static string SilmarillionMM {
            get {
                return ResourceManager.GetString("SilmarillionMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionNB.
        /// </summary>
        public static string SilmarillionNB {
            get {
                return ResourceManager.GetString("SilmarillionNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionNC.
        /// </summary>
        public static string SilmarillionNC {
            get {
                return ResourceManager.GetString("SilmarillionNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionUA.
        /// </summary>
        public static string SilmarillionUA {
            get {
                return ResourceManager.GetString("SilmarillionUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionVS.
        /// </summary>
        public static string SilmarillionVS {
            get {
                return ResourceManager.GetString("SilmarillionVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilmarillionYG.
        /// </summary>
        public static string SilmarillionYG {
            get {
                return ResourceManager.GetString("SilmarillionYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone.
        /// </summary>
        public static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
