//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.LordOfTheRingsFigures.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.LordOfTheRingsFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Aragorn / Sauron
        ///            
        ///Move:     
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///
        ///Attack: Kills all units to tile
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬛⬜⬜
        ///⬛⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬛▣⬛⬛⬛⬛⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬜⬛⬜⬛⬜⬜⬜
        ///        .
        /// </summary>
        internal static string AragornSauron_Description {
            get {
                return ResourceManager.GetString("AragornSauron_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aragorn / Sauron.
        /// </summary>
        internal static string AragornSauron_Name {
            get {
                return ResourceManager.GetString("AragornSauron_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Frodo / Gollum
        ///            
        ///Move:    
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬜⬛▣⬛⬜⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///            
        ///Attack:
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜     
        ///            
        ///Special: Can swap with any friendly unit
        ///        .
        /// </summary>
        internal static string FrodoGollum_Description {
            get {
                return ResourceManager.GetString("FrodoGollum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frodo / Gollum.
        /// </summary>
        internal static string FrodoGollum_Name {
            get {
                return ResourceManager.GetString("FrodoGollum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gandalf / Witch-king
        ///            
        ///Move:  
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬛⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬛⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬛⬜
        ///⬛⬛⬜⬛⬛⬜⬜⬜
        ///⬛⬜▣⬜⬛⬜⬛⬜
        ///⬛⬛⬜⬛⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬛⬜
        ///            
        ///Attack:
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜     
        ///        .
        /// </summary>
        internal static string GandalfWitchKing_Description {
            get {
                return ResourceManager.GetString("GandalfWitchKing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gandalf / Witch-king.
        /// </summary>
        internal static string GandalfWitchKing_Name {
            get {
                return ResourceManager.GetString("GandalfWitchKing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gimli / The Nazgûl
        ///            
        ///Move:    
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬛
        ///⬜⬜⬜⬜⬜⬜⬛⬜
        ///⬜⬜⬜⬜⬜⬛⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///            
        ///Attack:
        ///            
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬛⬛▣⬛⬛⬛⬛⬛
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜     
        ///        .
        /// </summary>
        internal static string GimliNazgul_Description {
            get {
                return ResourceManager.GetString("GimliNazgul_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimli / Nazgûl.
        /// </summary>
        internal static string GimliNazgul_Name {
            get {
                return ResourceManager.GetString("GimliNazgul_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Legolas / The Nazgûl
        ///            
        ///Move:      
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬛
        ///⬜⬜⬜⬜⬜⬜⬛⬜
        ///⬜⬜⬜⬜⬜⬛⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///            
        ///Attack:
        ///            
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬛⬛▣⬛⬛⬛⬛⬛
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜   
        ///        .
        /// </summary>
        internal static string LegolasNazgul_Description {
            get {
                return ResourceManager.GetString("LegolasNazgul_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legolas / Nazgûl.
        /// </summary>
        internal static string LegolasNazgul_Name {
            get {
                return ResourceManager.GetString("LegolasNazgul_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LordOfTheRings.
        /// </summary>
        internal static string LordOfTheRingsFigureGroup_Name {
            get {
                return ResourceManager.GetString("LordOfTheRingsFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Meriadoc Brandybuck / Troll
        ///   
        ///Move:      
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬛▣⬛⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///   
        ///Attack:      
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜▣⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///        .
        /// </summary>
        internal static string MerryTroll_Description {
            get {
                return ResourceManager.GetString("MerryTroll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merry / Troll.
        /// </summary>
        internal static string MerryTroll_Name {
            get {
                return ResourceManager.GetString("MerryTroll_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Peregrin Took / Troll
        ///   
        ///Move:    
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬛▣⬛⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///   
        ///Attack:         
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜▣⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬜⬜⬜⬜       
        ///        .
        /// </summary>
        internal static string PipinTroll_Description {
            get {
                return ResourceManager.GetString("PipinTroll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipin / Troll.
        /// </summary>
        internal static string PipinTroll_Name {
            get {
                return ResourceManager.GetString("PipinTroll_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Samwise Gamgee / Saruman
        ///            
        ///Move:    
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬜⬛▣⬛⬜⬜⬜⬜
        ///⬜⬛⬛⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///            
        ///Attack:
        ///            
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬜⬜▣⬜⬜⬜⬜⬜
        ///⬜⬛⬜⬛⬜⬜⬜⬜
        ///⬛⬜⬜⬜⬛⬜⬜⬜    
        ///            
        ///Special: Can swap with any friendly unit      
        ///        .
        /// </summary>
        internal static string SamSaruman_Description {
            get {
                return ResourceManager.GetString("SamSaruman_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sam / Saruman.
        /// </summary>
        internal static string SamSaruman_Name {
            get {
                return ResourceManager.GetString("SamSaruman_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The Guards of the Citadel / Orcs
        ///
        ///Move:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬛⬜⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬛⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜  
        ///
        ///Attack:
        ///
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///⬜⬜⬛⬜⬛⬜⬜⬜
        ///⬜⬜⬜▣⬜⬜⬜⬜
        ///⬜⬜⬜⬜⬜⬜⬜⬜
        ///
        ///Special: If initial position, can move further 
        ///        .
        /// </summary>
        internal static string SoldierOrc_Description {
            get {
                return ResourceManager.GetString("SoldierOrc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier / Ork.
        /// </summary>
        internal static string SoldierOrc_Name {
            get {
                return ResourceManager.GetString("SoldierOrc_Name", resourceCulture);
            }
        }
    }
}
