//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.LordOfTheRingsFigures.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.LordOfTheRingsFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Aragorn
        ///            
        ///Aragorn II, the son of Arathorn II and Gilraen, also known as Elessar and Strider, was the 16th Chieftain of the Dúnedain of the North; later crowned King Elessar Telcontar (March 1, 2931 - FO 120 or SR 1541), the 26th King of Arnor, and the 35th King of Gondor and first High King of Gondor and Arnor since the short reign of Isildur. He was a great warrior, and as Isildur&apos;s heir he bore the shards of Narsil, reforged and renamed Andúril, in the War of the Ring.
        ///            
        ///Sauron [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AragornSauron_Description {
            get {
                return ResourceManager.GetString("AragornSauron_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aragorn / Sauron.
        /// </summary>
        public static string AragornSauron_Name {
            get {
                return ResourceManager.GetString("AragornSauron_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Frodo
        ///         
        ///Frodo Baggins, son of Drogo Baggins, was a Hobbit of the Shire during the Third Age. He was, and still is, Tolkien&apos;s most renowned character for his leading role in the Quest of the Ring, in which he bore the One Ring to Mount Doom, where it was destroyed. He was a Ring-bearer, best friend to his gardener, Samwise Gamgee, and one of the three Hobbits who sailed from Middle-earth to the Uttermost West at the end of the Third Age.
        ///            
        ///Gollum
        ///
        ///Gollum, originally known as Sméago [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FrodoGollum_Description {
            get {
                return ResourceManager.GetString("FrodoGollum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frodo / Gollum.
        /// </summary>
        public static string FrodoGollum_Name {
            get {
                return ResourceManager.GetString("FrodoGollum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gandalf
        ///   
        ///Gandalf (Norse; IPA: [gand:alf] - \&quot;Elf of the Wand\&quot; or \&quot;Wand-elf\&quot;) the Grey, later known as Gandalf the White, and originally named Olórin (Quenya; IPA: [oˈloːrin] - \&quot;Dreamer\&quot; or \&quot;Of Dreams\&quot;), was an Istar (wizard), sent by the West in the Third Age to combat the threat of Sauron. He joined Thorin and his company to reclaim the Lonely Mountain from Smaug, convoked the Fellowship of the Ring to destroy the One Ring, and led the Free Peoples in the final campaign of the War of the Ring [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GandalfWitchKing_Description {
            get {
                return ResourceManager.GetString("GandalfWitchKing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gandalf / Witch-king.
        /// </summary>
        public static string GandalfWitchKing_Name {
            get {
                return ResourceManager.GetString("GandalfWitchKing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gimli
        ///   
        ///Gimli, son of Glóin, was a well-respected dwarf warrior in Middle-earth during the Great Years. He was a member of the Fellowship of the Ring, and was the only one of the dwarves to readily fight alongside elves in the war against Sauron at the end of the Third Age. After the defeat of Sauron, he was given lordship of the Glittering Caves at Helm&apos;s Deep.
        ///            
        ///The Nazgûl
        ///
        ///The Nazgûl (also known as Ringwraiths, The Nine, The Fallen Kings, Black Riders, Nunbolg, or Ulairi in Quenya) w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GimliNazgul_Description {
            get {
                return ResourceManager.GetString("GimliNazgul_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimli / Nazgûl.
        /// </summary>
        public static string GimliNazgul_Name {
            get {
                return ResourceManager.GetString("GimliNazgul_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Legolas
        ///
        ///Legolas was a Sindarin elf who was part of the Fellowship of the Ring in the Third Age. As he was the son of the Elvenking Thranduil of Mirkwood, Legolas was Prince of the Woodland Realm (Mirkwood), a messenger, and a master bowman. With his keen eyesight, sensitive hearing, and excellent bowmanship, Legolas was a valuable resource to the other members of the Fellowship. He was well-known for becoming friends with the dwarf Gimli, despite their long-held differences. It is not known whether Leg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LegolasNazgul_Description {
            get {
                return ResourceManager.GetString("LegolasNazgul_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legolas / Nazgûl.
        /// </summary>
        public static string LegolasNazgul_Name {
            get {
                return ResourceManager.GetString("LegolasNazgul_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LordOfTheRings.
        /// </summary>
        public static string LordOfTheRingsFigureGroup_Name {
            get {
                return ResourceManager.GetString("LordOfTheRingsFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Meriadoc Brandybuck
        ///   
        ///Meriadoc \&quot;Merry\&quot; Brandybuck (later known as Meriadoc \&quot;Merry\&quot; Brandybuck I, due to his grandson&apos;s birth) was a Hobbit and one of Frodo&apos;s cousins and closest friends. He loved boats and ponies and had a great interest in the maps of Middle-earth. He was also one of the nine companions in The Fellowship of the Ring.            
        ///
        ///Troll
        ///            
        ///Trolls were a very large and monstrous (ranging from between 10-18 feet tall), and for the most part unintelligent (references ar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MerryTroll_Description {
            get {
                return ResourceManager.GetString("MerryTroll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merry / Troll.
        /// </summary>
        public static string MerryTroll_Name {
            get {
                return ResourceManager.GetString("MerryTroll_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Peregrin Took
        ///   
        ///Peregrin Took, more commonly known as Pippin, was a Hobbit of the Shire, and one of Frodo Baggins&apos;s youngest, but closest friends. He was a member of the Fellowship of the Ring.            
        ///
        ///Troll
        ///            
        ///Trolls were a very large and monstrous (ranging from between 10-18 feet tall), and for the most part unintelligent (references are made about more cunning trolls), humanoid race inhabiting Middle-earth.            
        ///        .
        /// </summary>
        public static string PipinTroll_Description {
            get {
                return ResourceManager.GetString("PipinTroll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipin / Troll.
        /// </summary>
        public static string PipinTroll_Name {
            get {
                return ResourceManager.GetString("PipinTroll_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Samwise Gamgee
        ///   
        ///Samwise Gamgee, also known as Sam, was a Hobbit of the Shire. He was Frodo Baggins&apos; gardener and best friend. Sam proved himself to be Frodo&apos;s closest and most dependable companion, the most loyal of the Fellowship of the Ring, and also played a necessary role in protecting Frodo and destroying the One Ring.            
        ///
        ///Saruman
        ///            
        ///Saruman (Quenya; IPA: [&apos;saruman] - \&quot;Man Of Skill\&quot;), also known as Saruman the White was an Istar (wizard), who lived in Middle-earth during [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SamSaruman_Description {
            get {
                return ResourceManager.GetString("SamSaruman_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sam / Saruman.
        /// </summary>
        public static string SamSaruman_Name {
            get {
                return ResourceManager.GetString("SamSaruman_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The Guards of the Citadel
        ///   
        ///The Guards of the Citadel, sometimes referred to as the Guards of the Tower of Gondor, were the warriors responsible for guarding the upmost level of Minas Tirith, especially the courtyard that held the fountain and the White Tree of Gondor, and gave way the thronehall. They served as personal bodyguards to the Kings of Gondor, and later to the Stewards of Gondor until King Aragorn II Elessar&apos;s coronation. They were mainly a stationary guard unit, rather than a mobile force [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SoldierOrc_Description {
            get {
                return ResourceManager.GetString("SoldierOrc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier / Ork.
        /// </summary>
        public static string SoldierOrc_Name {
            get {
                return ResourceManager.GetString("SoldierOrc_Name", resourceCulture);
            }
        }
    }
}
