//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleChess3.SilmarillionFigures.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleChess3.SilmarillionFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Aulë
        ///
        ///Aulë(Quenya; IPA: [ˈaʊle] - \&quot;Invention\&quot;) was an Ainur, one of the Aratar and a Valar, who was responsible for fashioning and crafting the substances of which Arda, the world, was composed. He was also called Mahal (Khuzdul; IPA: \&quot;Maker\&quot;), Oli(Sindarin; IPA: \&quot;Dream\&quot;) or Návatar and delights in the nature of substances and in works of skill, but not concerned with possession or mastery.Besides the shaping of Arda, Aulë&apos;s greatest works were the Two Lamps of the Valar, the vessels of the Sun an [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AuleGothmog_Description {
            get {
                return ResourceManager.GetString("AuleGothmog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aulë / Gothmog.
        /// </summary>
        public static string AuleGothmog_Name {
            get {
                return ResourceManager.GetString("AuleGothmog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Elf
        ///   
        ///The Elves, who called themselves the Quendi, and who in lore are commonly referred to as the Eldar (adj. Eldarin), were the first and eldest of the Children of Ilúvatar, and are considered to be the fairest and wisest of any race of Arda given sapience. Some, known afterwards as the Calaquendi(Elves of the Light), were brought by the Valar from Middle-earth to Valinor across the Sea, where they were taught by the Ainur.But after the Silmarils were stolen by Melkor, some of the Elves returned to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ElfOrc_Description {
            get {
                return ResourceManager.GetString("ElfOrc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf / Orc.
        /// </summary>
        public static string ElfOrc_Name {
            get {
                return ResourceManager.GetString("ElfOrc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Irmo
        ///   
        ///Irmo (Quenya; IPA: [ˈirmo] - \&quot;Desirer\&quot; or \&quot;Master of Desires\&quot;) is an Ainu, and a Vala who was responsible for the creation of dreams and desires as well as visions too. He was more commonly known as Lórien, after the name of his dwelling place. Irmo-Lórien was the younger brother of Námo who also like his brother was commonly known as Mandos the name of his dwelling place, and also the brother of Nienna (Lady of Pity and Mourning).
        ///            
        ///Ungoliant
        ///
        ///Ungoliant (Sindarin IPA: [uŋˈɡo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IrmoUngoliant_Description {
            get {
                return ResourceManager.GetString("IrmoUngoliant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irmo / Ungoliant.
        /// </summary>
        public static string IrmoUngoliant_Name {
            get {
                return ResourceManager.GetString("IrmoUngoliant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LordOfTheRings.
        /// </summary>
        public static string LordOfTheRingsFigureGroup_Name {
            get {
                return ResourceManager.GetString("LordOfTheRingsFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Manwë
        ///   
        ///Manwë (Quenya; IPA: [ˈmanʷe] - \&quot;Blessed One\&quot;) was the leader of the Ainur, one of the Aratar, King of the Valar, husband of Varda, brother of the Dark Lord Melkor, and King of Arda. He was also known as Súlimo, Mânawenûz or Valahiru and lives atop Mount Taniquetil in Valinor, the highest mountain of the world. The winds and airs are his servants. He was the greatest in authority, but not in power, of all the Valar, Melkor being more powerful. He was however the greatest of the Aratar, among  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ManweMelkor_Description {
            get {
                return ResourceManager.GetString("ManweMelkor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manwë / Melkor.
        /// </summary>
        public static string ManweMelkor_Name {
            get {
                return ResourceManager.GetString("ManweMelkor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Nienna
        ///
        ///Nienna (Quenya; IPA [niˈenna] or [niˈjenna] - \&quot;Weeping\&quot; or \&quot;She Who Weeps\&quot;) was an Ainu, one of the Aratar and a Vala who was responsible for the mercy and grief spread across Arda. She was the sister of Mandos and Irmo and had no spouse. Her part in the Music of the Ainur was one of deep sadness, from which grief entered the world at its beginning. She had dominion over the Halls of Nienna, which were on the western edge of Valinor, looking over the sea.
        ///           
        ///Balrog
        ///
        ///Balrogs, als [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NiennaBalrog_Description {
            get {
                return ResourceManager.GetString("NiennaBalrog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nienna / Balrog.
        /// </summary>
        public static string NiennaBalrog_Name {
            get {
                return ResourceManager.GetString("NiennaBalrog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Oromë
        ///   
        ///Oromë (Quenya; IPA: [ˈorome] - &quot;Horn-Blower&quot; or &quot;Sound of Horns&quot;), also known as Aldaron (Quenya; IPA: &quot;Horn-Blower&quot;), Araw (Sindarin; IPA: &quot;Horn-Blower&quot;) or Arômêz, was an Ainu, one of the Aratar and a Vala who was responsible for the hunt. He was the brother of Nessa and the husband of Vána.            
        ///
        ///Carcharoth
        ///            
        ///Carcharoth, also known as the Red Maw, lived in the First Age of the Sun, and was the greatest werewolf who ever lived. He was of the line of Draugluin.
        ///        .
        /// </summary>
        public static string OromeCarcharoth_Description {
            get {
                return ResourceManager.GetString("OromeCarcharoth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oromë / Carcharoth.
        /// </summary>
        public static string OromeCarcharoth_Name {
            get {
                return ResourceManager.GetString("OromeCarcharoth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Ulmo
        ///   
        ///Ulmo (Quenya; IPA: [ˈulmo] - \&quot;Pourer\&quot; or \&quot;Rainer\&quot;) - also known as Ulubôz or Ullubôz - was an Ainu, one of the Aratar, and the Vala responsible for the control over the oceans of Arda. A lover of water, Ulmo was one of the Arda&apos;s chief architects and was always in a close friendship with Manwë. He always distrusted Melkor, and the Dark Lord feared the Sea almost as much as he feared Varda because the sea cannot be tamed. Ulmo had no dwelling in Valinor or any permanent dwelling on land, as  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UlmoAncalagon_Description {
            get {
                return ResourceManager.GetString("UlmoAncalagon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulmo / Ancalagon.
        /// </summary>
        public static string UlmoAncalagon_Name {
            get {
                return ResourceManager.GetString("UlmoAncalagon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Varda
        ///   
        ///Varda (Quenya; IPA: [ˈvarda] - \&quot;Sublime\&quot; or \&quot;Lofty\&quot;) is an Ainu, and one of the Aratar and a Vala who was responsible for the outlining of the stars in the heavens above Arda. She was also known as Elbereth (Sindarin; IPA: \&quot;Queen of the Stars\&quot;) or Gilthoniel, and was the spouse of Manwë, with whom she lives in Ilmarin on the summit of Taniquetil in Aman.       
        ///
        ///Sauron
        ///            
        ///Sauron (or Þauron (Thauron); Quenya; IPA: [ˈsaʊron] or Vanyarin; IPA: [ˈθaʊron] - \&quot;The Abhorred\&quot;), th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VardaSauron_Description {
            get {
                return ResourceManager.GetString("VardaSauron_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varda / Sauron.
        /// </summary>
        public static string VardaSauron_Name {
            get {
                return ResourceManager.GetString("VardaSauron_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Yavanna
        ///   
        ///Yavanna (Quenya; IPA: [jaˈvanna] - \&quot;Giver of Fruits\&quot;) was of the Ainur and Valar, and one of the Aratar who was responsible for the growth of all the fruits and growing things of Arda. She was also called Kementári (Quenya; IPA: \&quot;Queen of the Earth\&quot;), Ivon (Sindarin; IPA: \&quot;Giver of Fruits\&quot;). She resided in the Pastures of Yavanna, in the south of Valinor. She is the wife of Aulë, older sister of Vána, and kin to Melian.
        ///
        ///Glaurung
        ///            
        ///Glaurung was the first terrestrial, fir [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YavannaGlaurung_Description {
            get {
                return ResourceManager.GetString("YavannaGlaurung_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yavanna / Glaurung.
        /// </summary>
        public static string YavannaGlaurung_Name {
            get {
                return ResourceManager.GetString("YavannaGlaurung_Name", resourceCulture);
            }
        }
    }
}
