//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace BattleChess3.HobbitFigures.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("BattleChess3.HobbitFigures.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Ori
        ///            
        ///Ori was a member of Thorin&apos;s Company of Dwarves. He, alongside his brothers Dori and Nori, are remote kinsman of Thorin.
        ///            
        ///Felgrom
        ///            
        ///Felgrom was the character created from LOTR: Two Towers which blows up the sewer grate to achieve entrance into Helms Deep. Warner Bros. elaborated upon the character, giving him a name and he is playable as a Tactician in their game: Guardians of Middle-earth. He is a suicide bomber, with several Orcish explosives strapped to his [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Helper_Description {
            get {
                return ResourceManager.GetString("Helper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper.
        /// </summary>
        public static string Helper_Name {
            get {
                return ResourceManager.GetString("Helper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbit.
        /// </summary>
        public static string HobbitFigureGroup_Name {
            get {
                return ResourceManager.GetString("HobbitFigureGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Galadriel
        ///            
        ///Galadriel was the co-ruler and Lady of Lothlórien alongside her husband, Lord Celeborn - however, neither of them took royal titles, as they only saw themselves as the Guardians of The Golden Wood. She was the only daughter and youngest child of Finarfin, prince of the Ñoldor and of Eärwen, whose cousin was Lúthien.Her elder brothers were Finrod Felagund, Orodreth, Angrod, and Aegnor. Galadriel was a niece of Fëanor, one of the most important elves of the First Age. She was one of [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Leader_Description {
            get {
                return ResourceManager.GetString("Leader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Leader_Name {
            get {
                return ResourceManager.GetString("Leader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Radagast
        ///            
        ///Radagast (Adûnaic; IPA: [&apos;radagast] - \&quot;Tender Of Beasts\&quot;) the Brown, also called Aiwendil (Quenya; IPA: [ai&apos;wendil] - \&quot;Bird-Friend\&quot;) was one of the five Wizards, or Istari. He was a good friend of Gandalf the Grey, whom he aided occasionally. Radagast was mainly concerned with the well-being of the plant and animal worlds, and thus did not participate heavily in the War of the Ring.
        ///
        ///Saruman
        ///            
        ///Saruman (Quenya; IPA: [&apos;saruman] - \&quot;Man Of Skill\&quot;), also known as Sa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MinorWizard_Description {
            get {
                return ResourceManager.GetString("MinorWizard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor wizard.
        /// </summary>
        public static string MinorWizard_Name {
            get {
                return ResourceManager.GetString("MinorWizard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Bilbo Baggins
        ///
        ///Bilbo Baggins was a hobbit of the Shire, the main protagonist of The Hobbit and a secondary character in The Lord of the Rings.      
        ///
        ///Gollum
        ///            
        ///Gollum, originally known as Sméagol (or Trahald), was at first a Stoor, one of the three early Hobbit-types. The name Gollum was derived from the sound of his disgusting gurgling, choking cough. His birth can be estimated to have happened in the year TA 2430. His death date is given as March 25, 3019. His life was extended far beyon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RingBearer_Description {
            get {
                return ResourceManager.GetString("RingBearer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring bearer.
        /// </summary>
        public static string RingBearer_Name {
            get {
                return ResourceManager.GetString("RingBearer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Steward of Gondor
        ///
        ///The Stewards of Gondor were firstly the chief high councillors to the Kings of Gondor and then the rulers of Gondor, until the return of the rightful ruler King Aragorn II Elessar.
        ///
        ///The Great Spiders
        ///
        ///The Great Spiders, also known as the Children of Ungoliant, were a race of oversized and sentient arachnids that lived in Middle-earth, particularly in dark and perilous places affected by the power of the Shadow.
        ///        .
        /// </summary>
        public static string Soldier_Description {
            get {
                return ResourceManager.GetString("Soldier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        public static string Soldier_Name {
            get {
                return ResourceManager.GetString("Soldier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Nori
        ///
        ///Nori was a Dwarf of Durin&apos;s folk who lived in the northern Blue Mountains in Thorin&apos;s Halls and later the restored Lonely Mountain. He had two brothers named Dori and Ori, and was a remote kinsman of Thorin Oakenshield. His hood was purple, he played the flute, and he was very fond of regular and plentiful meals like his hobbit friend, Bilbo Baggins.
        ///
        ///Gothmog
        ///
        ///Gothmog was the lieutenant of the Witch-king in the Third Age, from Minas Morgul, notably at the Battle of the Pelennor Fields.
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Warrior_Description {
            get {
                return ResourceManager.GetString("Warrior_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string Warrior_Name {
            get {
                return ResourceManager.GetString("Warrior_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Gandalf
        ///
        ///Gandalf (Norse; IPA: [gand:alf] - \&quot;Elf of the Wand\&quot; or \&quot;Wand-elf\&quot;) the Grey, later known as Gandalf the White, and originally named Olórin (Quenya; IPA: [oˈloːrin] - \&quot;Dreamer\&quot; or \&quot;Of Dreams\&quot;), was an Istar (wizard), sent by the West in the Third Age to combat the threat of Sauron. He joined Thorin and his company to reclaim the Lonely Mountain from Smaug, convoked the Fellowship of the Ring to destroy the One Ring, and led the Free Peoples in the final campaign of the War of the Ring.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wizard_Description {
            get {
                return ResourceManager.GetString("Wizard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard_Name {
            get {
                return ResourceManager.GetString("Wizard_Name", resourceCulture);
            }
        }
    }
}
